CREATE TABLE principle_groups
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255)                            NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_principle_groups PRIMARY KEY (id)
);

ALTER TABLE principle_groups
    ADD CONSTRAINT uc_principle_groups_code UNIQUE (code);