CREATE TABLE "user"
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name            VARCHAR(255),
    last_name             VARCHAR(255),
    email                 VARCHAR(255),
    password              VARCHAR(255),
    token                 VARCHAR(255),
    account_verified      BOOLEAN                                 NOT NULL,
    failed_login_attempts INTEGER                                 NOT NULL,
    login_disabled        BOOLEAN                                 NOT NULL,
    mfa_enabled           BOOLEAN                                 NOT NULL,
    secret                VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_groups
(
    customer_id BIGINT NOT NULL,
    group_id    BIGINT NOT NULL,
    CONSTRAINT pk_user_groups PRIMARY KEY (customer_id, group_id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE user_groups
    ADD CONSTRAINT fk_usegro_on_group FOREIGN KEY (group_id) REFERENCES principle_groups (id);

ALTER TABLE user_groups
    ADD CONSTRAINT fk_usegro_on_user_entity FOREIGN KEY (customer_id) REFERENCES "user" (id);