CREATE TABLE secure_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    time_stamp  TIMESTAMP WITHOUT TIME ZONE,
    expire_at   TIMESTAMP WITHOUT TIME ZONE,
    customer_id BIGINT,
    CONSTRAINT pk_securetokens PRIMARY KEY (id)
);

ALTER TABLE secure_tokens
    ADD CONSTRAINT uc_securetokens_token UNIQUE (token);

ALTER TABLE secure_tokens
    ADD CONSTRAINT FK_SECURETOKENS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES "user" (id);