CREATE TABLE customers
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    service_rendered VARCHAR(255),
    address          VARCHAR(255),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);