DB_IP: 127.0.0.1
DB_PORT: 5433
DB_DATABASE_NAME: company
DB_URL: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_DATABASE_NAME}
DB_USERNAME: postgres
DB_PASSWORD: postgres
DB_SCHEMA: public




#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  flyway:
#    baseline-on-migrate: true
#    locations: classpath:db/migrations
#    create-schemas: true
#    default-schema: ${DB_SCHEMA}
#    enabled: true
#
#  jpa:
#    open-in-view: false
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        jdbc:
#          # Fix Postgres JPA Error (Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented).
#          lob.non_contextual_creation: true
#          time_zone: UTC
#          # to avoid name conflict of custom table objects
#          # with object names in PostgresSQL
#      auto_quote_keyword: true

logging:
  level:
    root: debug
    reactor: debug
    org:
      easy:
        email: debug
      springframework:
        web: debug
        security: trace
        security.oauth2: trace
